services:
  - type: web
    name: anime-backend-api
    runtime: node
    repo: https://github.com/KunNew/anime-backend-api
    plan: free
    envVars:
      - key: BACKEND_URL
        value: https://api.amvstr.me/api/v2
      - key: BASE_BACKEND_URL
        value: https://api.amvstr.me
      - key: NODE_ENV
        value: "production"
      - key: BUN_VERSION
        value: "1.1.43"
    region: oregon
    buildCommand: bun install
    startCommand: bun start
version: "1"
